/*
Lenguaje DDL Lenguaje de definicion de datos 
CREATE
ALTER
DROP
TRUNCATE
RENAME
*/
-- CREAMOS LA BASE DE DATAS
CREATE DATABASE PRUEBA;

use prueba;
-- CREAR UNA TABLA
CREATE TABLE productos(
 id INT  PRIMARY KEY AUTO_INCREMENT,
 nombre VARCHAR(30) NOT NULL,
 precio DECIMAL(10,2) 
);

-- AGREGAR NUEVO PRODUCTO A LA TABLA productos
ALTER TABLE productos ADD STOCK INT;

-- RENOMBRAR TABLA
RENAME TABLE productos TO inventario;



-- ELIMINAR LA BASE DE DATOS
DROP TABLE inventario;


